# Generated by Django 5.2.5 on 2025-08-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_alter_quote_weight_quotereaction_delete_quotescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotereaction',
            name='is_like',
        ),
        migrations.AddField(
            model_name='quotereaction',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10, null=True),
        ),
    ]
