# Generated by Django 5.2.5 on 2025-09-03 22:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quotereaction_is_like_quotereaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
